services:
  scielo-web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/rocky9/Dockerfile
    container_name: scielo-web-rocky9
    network_mode: host
    environment:
      HTTPD_PORT: "8090"
      SERVER_SCIELO: "educa.fcc.org.br"
      SCIELO_ENABLE_DEBUG: "1"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
