ServerName localhost

DocumentRoot "/var/www/html/htdocs"
DirectoryIndex scielo.php index.php index.html

Alias /pdf/ "/var/www/html/bases/pdf/"

<Directory "/var/www/html/htdocs">
    Options -Indexes +FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<DirectoryMatch "^/var/www/html/htdocs/.*/(Examples|samples|test)(/.*)?$">
    Require all denied
</DirectoryMatch>

<LocationMatch "^/.*/(Examples|samples|test)(/.*)?$">
    Require all denied
</LocationMatch>

<Directory "/var/www/html/htdocs/applications/scielo-org/includes/nusoap/samples">
    Require all denied
</Directory>

<Directory "/var/www/html/htdocs/applications/scielo-org/includes/phpmailer/test">
    Require all denied
</Directory>

<Directory "/var/www/html/htdocs/applications/scielo-org/includes/jpgraph-1.20.4/src/Examples">
    Require all denied
</Directory>

<Directory "/var/www/html/bases/pdf/">
    Options -Indexes +FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

<Directory "/var/www/html/cgi-bin">
    Options -Indexes +ExecCGI -FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
